@HostAddress = http://localhost:5133

GET {{HostAddress}}/forex/eur
Accept: application/json

###
GET {{HostAddress}}/forex/usd/convert/aud
Accept: application/json

###
GET {{HostAddress}}/forex/eur/convert/aud?amount=1000
Accept: application/json

###
GET {{HostAddress}}/forex/eur/convert/try
Accept: application/json

###
GET {{HostAddress}}/forex/eur/history?startDate=2025-02-08
Accept: application/json

###
GET {{HostAddress}}/forex/eur/history?startDate=2025-02-07&endDate=2025-02-10
Accept: application/json

###
GET {{HostAddress}}/forex/eur/history?startDate=2025-02-07&endDate=2025-02-01
Accept: application/json

###
